version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: my-remix-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  app:
    build: .
    container_name: todo-app
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      
volumes:
  postgres_data: